from enum import Enum


class Price(Enum):
    PLAN_BASIC_PRICE = 250
    PLAN_STREAM_BASIC_PRICE = 350
    PLAN_MEDIUM_PRICE = 350
    PLAN_STREAM_MEDIUM_PRICE = 450
    PLAN_GEEK_PRICE = 450
    PLAN_STREAM_GEEK_PRICE = 550
