from enum import Enum


class  Velocity(Enum):
    PLAN_BASIC_VELOCITY = 15
    PLAN_STREAM_BASIC_VELOCITY = 20
    PLAN_MEIDUM_VELOCITY = 25
    PLAN_STREAM_MEDIUM_VELOCITY = 30
    PLAN_GEEK_VELOCITY = 40
    PLAN_STREAM_GEEK_VELOCITY = 50
